FROM node:19.4 as build

WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .

ENV VITE_API_URI=http://176.147.134.208:3000
RUN npm run build

FROM nginx:latest

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf