FROM node:19.4 as build

WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .
RUN npm build

FROM nginx:latest

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf